twig:
    default_path: '%kernel.project_dir%/templates'

when@test:
    twig:
        strict_variables: true

#twig.extension.text:
#    class: Twig_Extensions_Extension_Text
#    tags:
#    - { name: twig.extension }