app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

        
#index:
#    path:     /{_locale}/
#    defaults: { _controller: AppBundle:Default:index }
#    requirements:
#        _locale: '%app.locales%'